### ISSUE TITLE
Give a brief roadmap summary on the  OpenStack and OpenNebula Integration pages

### ISSUE THREAD

**Issue by brucellino** [EGI-Foundation/fedcloud-integration-documentation#15]
# Short Description of the issue

The [section on integrating cloud stacks](https://egi-federated-cloud-integration.readthedocs.io/en/latest/integration.html#) gives detailed information about how to integrate specific stacks. I found that, though complete, it lacks a sense of direction. The ignorant reader is led without really understanding what the intermediate steps and final goal are, and this makes it difficult to follow the document and understand which section one is currently in.

# Summary of proposed changes

I propose : 
  1. Number the sections
  1. Provide a paragraph in the beginning or [at the overview](https://egi-federated-cloud-integration.readthedocs.io/en/latest/integration.html) describing the journey one would take to get to the full integration.

**Comment by gwarf** [comment]
Done on https://docs.egi.eu/providers/cloud-compute/
