### ISSUE TITLE
EGI CAs installation

### ISSUE THREAD

**Issue by cyrilletoulet** [EGI-Foundation/fedcloud-integration-documentation#31]
There is no CAs in _/etc/grid-security/certificates/_ for new sites using manual configuration.
I think those CAs are required by AAI mechanisms.

On my site, I've installed the following packages from EGI-trustanchors repository:
- ca_DigiCertGridRootCA-Root
- ca_seegrid-ca-2013
- ca-policy-egi-core

May it be a lack in the documentation?

**Comment by gwarf** [comment]
Bonjour Cyrille,
In fact we added some info here: https://egi-federated-cloud-integration.readthedocs.io/en/latest/openstack.html#pre-requisites
That should give some pointers, please have a look and let us know (or propose using a PR :) ) what is missing/unclear.

**Comment by gwarf** [comment]
And `ca-policy-egi-core` should probably cover everthing that should be present.
https://galaxy.ansible.com/egi-foundation/umd could be interesting if you are into ansible.

And don't hesitate to provide feedback (here or by email) on the missing/complex points that should be covered more precisely, we are looking for this kind of feedback to be able to make this documentation more user friendly.

**Comment by cyrilletoulet** [comment]
Bonjour Baptiste,

According to the doc, the ca-policy-egi-core and the fetch-crl packages are installed for the optional VOMS support. In my case, I've don't configured it.

So I suggest to move this part into _Integration > OpenStack > EGI AAI_ section.

For the global feedback, I'm actually browsing my installation notes to confront their with the current version of the documentation.

**Comment by gwarf** [comment]
We are archiving this repository, if this still applies please open a new issue at https://github.com/EGI-Foundation/documentation.
