### ISSUE TITLE
Feddback on OpenStack integration procedure

### ISSUE THREAD

**Issue by cyrilletoulet** [EGI-Foundation/fedcloud-integration-documentation#32]
As announced in issue #31, I've browsed my installation notes to confront them with the current version of the documentation.

All the lacks I'd noticed during the UNIV-LILLE site certification were fixed with several commits.

A remaining question: I've seen, commented in openstack.rst source file, the documentation for cASO and SSMsend using individual components. 

Why these lines are commented? These informations would've been very useful during our integration ;~)

Otherwise, good job!

**Comment by enolfc** [comment]
Thanks for the feedback @cyrilletoulet!

The lines are commented because we never certified that it was working and packages were not available in CMD when written. 

When #9 is fixed, this should be done.

**Comment by gwarf** [comment]
We are archiving this repository, if this still applies please open a new issue at https://github.com/EGI-Foundation/documentation.
