### ISSUE TITLE
Move issues to https://github.com/EGI-Foundation/documentation.

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/fedcloud-integration-documentation#40]
In order to ease documentation discovery content should be moved to https://github.com/EGI-Foundation/documentation.

**Comment by enolfc** [comment]
Done :)

**Comment by gwarf** [comment]
Not that fast :)
We should close/move the issues, add a redirection info in the readme and in readthedocs and then archive the repository.

**Comment by gwarf** [comment]
Re-opening, we still need to move all tasks

**Comment by gwarf** [comment]
Done!
