### ISSUE TITLE
Confused about what needs to be enabled in the scope field

### ISSUE THREAD

**Issue by daikema** [EGI-Foundation/fedcloud-integration-documentation#42]
On https://github.com/EGI-Foundation/fedcloud-integration-documentation/blob/master/source/openstack.rst there's a note that one should "Enable openid, profile, email, eduperson_entitlement _and_ in the Scope field".  

That "and" is somewhat ambiguous though.  The sentence would read fine with it deleted, but that's not he only possible interpretation.  `eduperson_scoped_affiliation` and `eduperson_unique_id` are attributes also selected by default and it could be that the "and" instead hints that the list of required selections is incomplete.

Currently I've kept the default selections as is in my testbed registration but am not sure this is what's required.

**Comment by gwarf** [comment]
Should have been addressed in https://docs.egi.eu/providers/cloud-compute/
