### ISSUE TITLE
Define actual versions of components at the documentation

### ISSUE THREAD

**Issue by kira2600** [EGI-Foundation/fedcloud-integration-documentation#50]
# Short Description of the issue
Define actual(working) versions of components at the integration [documentation](https://github.com/EGI-Foundation/fedcloud-integration-documentation/blob/master/source/openstack.rst)

# Summary of proposed changes
Would be nice to see at the integration [documentation](https://github.com/EGI-Foundation/fedcloud-integration-documentation/blob/master/source/openstack.rst) page the actual versions of components with links to dockerhub.

**Comment by gwarf** [comment]
Dear @kira2600, thanks but this documentation space is outdated, you should check https://docs.egi.eu/.
If needed you can open an issue at https://github.com/EGI-Foundation/documentation.
