### ISSUE TITLE
Access to VO wide image lists

### ISSUE THREAD

**Issue by enolfc** [EGI-Foundation/fedcloud-integration-documentation#7]
* [https://wiki.appdb.egi.eu/main:faq:how_to_get_access_to_vo-wide_image_lists get access to VO wide image lists]
   * [https://wiki.appdb.egi.eu/main:faq:how_to_subscribe_to_a_private_image_list_using_the_vmcatcher subscribe to a private image list]

**Comment by gwarf** [comment]
Documented in https://docs.egi.eu/providers/cloud-compute/openstack/#egi-vm-image-management
